apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring      
  labels:
    release: prometheus     
spec:
  selector:
    matchLabels:
      app: backend         
  namespaceSelector:
    matchNames:
      - todo-app              
  endpoints:
    - port: http             
      interval: 15s
      path: /metrics  
