apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring        # مكان تشغيل Prometheus Operator عادة
  labels:
    release: prometheus       # لازم يتوافق مع label في Prometheus Operator (تأكد منه)
spec:
  selector:
    matchLabels:
      app: backend            # نفس اللابل في سيرفيس الـ backend
  namespaceSelector:
    matchNames:
      - todo-app              # النيمسبيس اللي فيه تطبيق backend
  endpoints:
    - port: http              # اسم البورت في الـ Service (اللي حطيناه في الخطوة 1)
      interval: 15s
      path: /metrics  
